from django.urls import re_path

from review.views import (
    build_graph,
    clusters_view,
    cluster_view,
    comparison,
    configure_course,
    course,
    course_histograms,
    dolos_proxy_api_view,
    dolos_proxy_view,
    dolos_hub,
    exercise,
    exercise_settings,
    flagged_pairs,
    generate_course_dolos_view,
    generate_cross_course_dolos_view,
    generate_dolos_view,
    go_to_dolos_view,
    graph_ui,
    index,
    invalidate_graph_cache,
    marked_submissions,
    pair_view,
    pair_view_summary,
    students_view,
    student_view,
    toggle_radar_mode,
)


urlpatterns = [
    re_path(
        r'^$',
        index,
        name='index'
    ),
    re_path(
        r'^toggle_radar$',
        toggle_radar_mode,
        name='toggle_radar_mode'
    ),
    re_path(
        r'^cross_course_dolos$',
        generate_cross_course_dolos_view,
        name='cross_course_dolos'
    ),
    re_path(
        r'^(?P<course_key>\w+)/$',
        course,
        name='course'
    ),
    re_path(
        r'^(?P<course_key>\w+)/course_dolos$',
        generate_course_dolos_view,
        name='course_dolos'
    ),
    re_path(
        r'^(?P<course_key>\w+)/dolos_hub/$',
        dolos_hub,
        name='dolos_hub'
    ),
    re_path(
        r'^(?P<course_key>\w+)/dolos_hub/(?P<exercise_key>\w+)/$',
        dolos_hub,
        name='dolos_hub_exercise'
    ),
    re_path(
        r'^(?P<course_key>\w+)/histogram/$',
        course_histograms,
        name='course_histograms'
    ),
    re_path(
        r'^(?P<course_key>\w+)/configure/$',
        configure_course,
        name='configure_course'
    ),
    re_path(
        r'^(?P<course_key>\w+)/marked/$',
        marked_submissions,
        name='marked_submissions'
    ),
    re_path(
        r'^(?P<course_key>\w+)/graph/$',
        graph_ui,
        name='graph_ui'
    ),
    re_path(
        r'^(?P<course_key>\w+)/clusters/$',
        clusters_view,
        name='clusters_view'
    ),
    re_path(
        # Cluster key must be integer
        r'^(?P<course_key>\w+)/clusters/(?P<cluster_key>\d+)/$',
        cluster_view,
        name='cluster_view'
    ),
    re_path(
        r'^(?P<course_key>\w+)/students/$',
        students_view,
        name='students_view'
    ),
    re_path(
        r'^(?P<course_key>\w+)/students/(?P<student_key>\w+)/$',
        student_view,
        name='student_view',
    ),
    re_path(
        r'^(?P<course_key>\w+)/(?P<a_key>\w+)-(?P<b_key>\w+)/$',
        pair_view,
        name='pair_view',
    ),
    re_path(
        r'^(?P<course_key>\w+)/(?P<a_key>\w+)-(?P<b_key>\w+)/summary/$',
        pair_view_summary,
        name='pair_view_summary',
    ),
    re_path(
        r'^(?P<course_key>\w+)/flagged_pairs/$',
        flagged_pairs,
        name='flagged_pairs'
    ),
    re_path(
        r'^(?P<course_key>\w+)/graph/build$',
        build_graph,
        name='build_graph'
    ),
    re_path(
        r'^(?P<course_key>\w+)/graph/invalidate$',
        invalidate_graph_cache,
        name='invalidate_graph_cache',
    ),
    re_path(
        r'^(?P<course_key>\w+)/(?P<exercise_key>\w+)/$',
        exercise,
        name='exercise'
    ),
    re_path(
        r'^(?P<course_key>\w+)/(?P<exercise_key>\w+)/settings/$',
        exercise_settings,
        name='exercise_settings',
    ),
    re_path(
        r'^(?P<course_key>\w+)/(?P<exercise_key>\w+)/compare/(?P<ak>\w+)-(?P<bk>\w+)/(?P<ck>\w+)$',
        comparison,
        name='comparison',
    ),
    re_path(
        r'^(?P<course_key>\w+)/(?P<exercise_key>\w+)/(?P<best_submissions>\w+)/(?P<flagged>\w+)/gen_dolos$',
        generate_dolos_view,
        name='dolos',
    ),
    re_path(
        r'^(?P<course_key>\w+)/(?P<exercise_key>\w+)/dolos$',
        go_to_dolos_view,
        name='go_to_dolos',
    ),
    re_path(
        r'^dolos-proxy/(?P<path>.*)$',
        dolos_proxy_view.as_view(),
        name='dolos_proxy'
    ),
    re_path(
        r'^dolos-api-proxy/(?P<path>.*)$',
        dolos_proxy_api_view.as_view(),
        name='dolos_api_proxy'
    ),
]
